# Generated by Django 2.2 on 2019-12-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
