# Generated by Django 2.2 on 2020-01-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200103_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='date_posted'),
        ),
    ]
